//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Castings = new HashSet<Casting>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Synopsis { get; set; }
        public string Author { get; set; }
        public int AudienceId { get; set; }
        public int StyleId { get; set; }
        public int Year { get; set; }
        public string PosterId { get; set; }
        public double RatingsAverage { get; set; }
        public int NbRatings { get; set; }
    
        public virtual Audience Audience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Casting> Castings { get; set; }
        public virtual Style Style { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
